const homeStyles = {
    container: {
      backgroundImage: `url(${process.env.PUBLIC_URL}/wallpaper.jpg)`,
      backgroundSize: 'cover',
      backgroundPosition: 'center',
      backgroundRepeat: 'no-repeat',
      height: '100vh',
      display: 'flex',
      justifyContent: 'center',
      alignItems: 'center',
      flexDirection: 'column',
      backgroundColor: '#121212',
      color: 'white',
    },
    header: {
      marginBottom: '20px',
      backgroundColor: '#1e1e2e',
      color: 'white',
      padding: '10px 20px',
      borderRadius: '5px',
      display: 'inline-block',
      fontSize: '5vh',
    },
    inputContainer: {
      display: 'flex',
      alignItems: 'center',
      gap: '10px',
    },
    input: {
      padding: '10px',
      fontSize: '16px',
      borderRadius: '5px',
      border: '1px solid #ccc',
    },
    searchButton: {
      padding: '10px 20px',
      fontSize: '16px',
      backgroundColor: 'grey',
      color: 'black',
      border: 'none',
      borderRadius: '5px',
      cursor: 'pointer',
    },
    modalContainer: {
      position: 'fixed',
      top: '50%',
      left: '50%',
      transform: 'translate(-50%, -50%)',
      width: '60vw',
      height: '80vh',
      backgroundColor: '#121212',
      display: 'flex',
      justifyContent: 'center',
      alignItems: 'center',
      zIndex: '1000',
      borderRadius: '10px',
      overflow: 'hidden',
      boxShadow: '0 4px 10px rgba(0, 0, 0, 0.5)',
    },
    modalContent: {
      backgroundColor: '#1e1e2e',
      color: 'white',
      padding: '20px',
      borderRadius: '10px',
      textAlign: 'center',
      width: '100%',
      height: '100%',
      overflowY: 'auto',
      boxShadow: '0 4px 10px rgba(0, 0, 0, 0.5)',
    },
    closeButton: {
      marginTop: '20px',
      padding: '10px 20px',
      backgroundColor: '#007bff',
      color: 'white',
      border: 'none',
      borderRadius: '5px',
      cursor: 'pointer',
    },
  };
  
  export default homeStyles;
  